config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :chats
  end

  post '/chats'=>"home#post_chat"
  root 'home#index'

end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :message
  validates_length_of :message,  :within => 2..150
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chats
  validates_presence_of :first_name, :last_name, :profile_name, :location, :photo_url
  validates_uniqueness_of :profile_name

  scope :by_profile_name, -> { order(user: :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :set_new_user
  # before_action :set_new_chat

  before_action :configure_permitted_parameters, if: :devise_controller?

  # def set_new_user
  #   @new_user = User.new
  # end

  # def set_new_chat
  #   @new_chat = Chat.new
  # end

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name, :profile_name, :location, :photo_url)
 end



end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.first

  end

  def new
    set_user
    set_new_chat
  end

  def create
    @chat = Chat.new(chat_params)
    user = User.find(params[:user_id])
    @chat.user_id = user.id
    respond_to do |format|
      if @chat.save
        format.html { redirect_to root_path, notice: 'Chat was successfully created.' }
        format.json { render :show, status: :created, location: @chat }
        # format.json { render json: @chat, status: :created, location: @chat }
        # format.html { render json: @chat, notice: 'Chat was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def delete
  end

  private
    def set_chat
      @chat = Chat.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def set_new_chat
      @new_chat = Chat.new
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_params
      params.require(:chat).permit(:message, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
protect_from_forgery with: :exception

  def index
    @user = User.first
    @chats = Chat.all.order("created_at DESC")
    @users = User.all
  end


  def new
    @user = User.new
    @chat = Chat.new
  end

  def post_chat
    @chat = Chat.new(chat_params)
    user = User.find(params[:user_id])
    @chat.user_id = user.id
    respond_to do |format|
      if @chat.save
        format.html { redirect_to root_path, notice: 'Chat was successfully created.' }
        format.json { render json: @chat.as_json, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { render chats_index_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render "home/index" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def set_chat
      @chat = Chat.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :profile_name, :location, :photo_url, :bio)
    end

    def chat_params
      params.require(:user).permit(:user_id, :message)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :index

  def index
    @users = User.all.order(:profile_name)
    @user = User.first
  end

  def show
    @user = User.find(params[:id])
    chats = Chat.all
    @chats = chats.where(user_id:@user_id)
  end

  def delete
  end

  def new
    @user = User.new
  end


def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render "home/index" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
    def set_user
      @user = User.find(params[:id])
    end


    def user_params
      params.require(:user).permit(:first_name, :last_name, :profile_name, :location, :photo_url, :bio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/chats_helper.rb
module ChatsHelper
  def user_collection
    User.select('id', 'profile_name').map { |user| [user.profile_name, user.id] } #=> [ [1, 'johndoe'], [2, 'janeSmith']]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/_chatform.html.erb
<%= simple_form_for([@user, @new_chat]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id, collection: user_collection %>
    <%= f.input :message %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/chats/new.html.erb
<h3 role="presentation">Create New Chat</h3>
    <p><%= render 'chatform' %></p>

app/views/home/_chatform.html.erb
<%= simple_form_for([current_user, Chat.new], remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :message %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="stripe">


<h1 class="title">Let's Chat!</h1>
</div>
<div class='container'>
  <div class="row">
    <div class="col-md-3">
    <br />
    <h3 role="presentation"><%= link_to 'Become A User', user_registration_path %></h3>

    <h3 role="presentation">Create New Chat</h3>
    <div id="chatform">
      <p><%= render 'chatform' %></p>
    </div>

    <script type="text/javascript">
      jQuery(function($) {
         $("#chatform")
           .on("ajax:loading", console.log('loading'))
           .on("ajax:complete", console.log('complete'))
           .on("ajax:success", function(event, data, status, xhr) {
             console.log(data);
           })
           .on("ajax:failure", function(xhr, status, error) {
             console.log(error);
           });
       });
</script>

</div>
    <div class="col-md-2">
    </div>
    <div class="col-md-7">
      <h3> Chats</h3><br />

      <% @chats.each do |chat| %>

            <p class="chats-main"><%= chat.message %></p>
            <p class="time-stamp"><span class="glyphicon glyphicon-time" aria-hidden="true"></span> Created <%= time_ago_in_words(chat.created_at) %> ago by: <span class="prof"><%= link_to chat.user.profile_name, user_path(chat.user) %></span></p>



      <% end %>
    </div>


</div>

app/views/layouts/_chatform.html.erb
<%= simple_form_for([@user, @new_chat]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :profile_name, collection: user_collection %>
    <%= f.input :message %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/layouts/_form.html.erb
<%= simple_form_for(@new_user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :profile_name %>
    <%= f.input :location %>
    <%= f.input :photo_url %>
    <%= f.input :bio %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


      <p class="notice"><%= notice %></p>

      <p class="alert"><%= alert %></p>






    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <div class="container">
      <div><h3 class="nav-title"> Chatter   <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>  Chatter   <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>  Chatter   <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>  Chatter   <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Chatter   <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>  Chatter   <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>  Chatter   </h3></div>

      <button type="button" class="btn btn-default navbar-btn btn-left"><%= link_to 'Home', root_path %></button>
      <button type="button" class="btn btn-default navbar-btn btn-left"><%= link_to 'View All Users', users_path %></button>
      <% if user_signed_in? %>
      <button type="button" class="btn btn-default navbar-btn btn-right"><%= link_to 'Create Chat', new_user_chat_path(@user) %></button>
      <% end %>
    </div>

  </nav>

  <% if user_signed_in? %>
    <%= link_to 'Logout', destroy_user_session_path(@current_user), method: :delete %>
  <% else %>
    <%= link_to 'Sign In', new_user_session_path %>
    <% end %>

    <%= yield %>


  <div class="footer">
  </div>



</div>
</body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :profile_name %>
    <%= f.input :location %>
    <%= f.input :photo_url %>
    <%= f.input :bio %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/users/create.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="stripe">


<h1 class="title">Chatter Users</h1>
</div>

<div class='container'>

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="8"></th>
    </tr>
  </thead>
  <tbody>
    <div id='users-container'>
      <tr>
        <% @users.each do |user| %>
          <td><span class="glyphicon glyphicon-user" aria-hidden="true"></span><p class="prof-name"> <%= link_to user.profile_name, user_path(user) %><%=  %> </p></td>
          <td><p class="photo"> <%= link_to(image_tag(user.photo_url), user) %></p> </td>
      </tr>
        <% end %>
    </div>
  </tbody>
  </table>
  </div>

app/views/users/show.html.erb
<p id="notice"> <%= notice %></p>


<div class="stripe">


<h1 class="title"><%= @user.profile_name.capitalize %>'s Profile Page</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-3">

      <span class="pic"> <%= link_to(image_tag(@user.photo_url), @user) %></span>
      <p class="profile-name"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span><strong> Profile Name: </strong><%= @user.profile_name %> </p>
      <p class="name"><span class="glyphicon glyphicon-user" aria-hidden="true"></span><strong>Name: </strong><%= @user.first_name %> <%= @user.last_name %></p>
      <p class="location"><span class="glyphicon glyphicon-globe" aria-hidden="true"></span><strong> Location: </strong><%= @user.location %></p>
      <p class="bio"><span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong> Bio: </strong><%= @user.bio %></p>
    </div>

    <div class="col-md-1">
    </div>

    <div class="col-md-7">
    <h3> <%= @user.profile_name.capitalize %>'s Chats</h3><br />
      <% @user.chats.each do |chat| %>
      <p class="chats">
      <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>
      <%= chat.message %> </p>
      <p class="time-stamp"><span class="glyphicon glyphicon-time" aria-hidden="true"></span> Created <%= time_ago_in_words(chat.created_at) %> ago</p>
      <% end %>

    </div>
  </div>
</div>